config/routes.rb
Rails.application.routes.draw do
  get 'video_tours/index'
  # resources :blogs
  get 'contacts/index'
  get 'payment_histories/index'
  get 'my_bookings/index'
  get 'user_rooms/index'
  get 'package_details/index'
  get 'user_hotels/index'
  get 'user_hotels/details'
  get 'user_places/index'
  get 'user_packages/index'
  get 'user_packages/details'
  get 'user_packages/filter'
  get 'video_tours/index'
  get 'video_tours/details'
  get 'blogs/blog_details'
  get 'details', to: "user_hotels#details"
  post 'rating', to: "user_hotels#set_hotel_rating"
  get 'search', to: "user_places#search"
  get 'filter_room', to: "user_rooms#filter_room"
  get 'min_max', to: "user_rooms#min_max"
  get 'filters_room', to: "user_packages#filters_room"
  get 'bookings/done'
  get 'contacts/done'
  get 'payment_histories/done'
  get 'rooms/justshow'
  get 'blogs/my_blog'
  resources :packages
  resources :bookings
  resources :contacts
  resources :payment_histories
  resources :rooms
  resources :hotels
  resources :places
  devise_for :users
  root to: 'home#index'

  # scope module: "users" do
  resources :blogs
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner

  has_rich_text :body
  def optimized_image(image,x,y)
    retrun image.variant(resize_to_fill: [x,y]).processed
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
   validates :name, :address, :contact_no, :email, :check_in_date, :check_out_date, presence: true
  validates :contact_no,   :presence => {:message => 'hello world, bad operation!'},
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  enum payment_status: {
    "unpaid" => 0,
    "paid" => 1,

  }
  belongs_to :user
  belongs_to :room
  has_one :payment_history

   # def paid_and_unpaid
   #   @booking = Booking.find(params[:booking_id])
   #   @booking.payment_history= PaymentHistory.find(params[:payment_history_id])
   #   if @booking.payment_histories_is_complete
   #     booking.payment_status = 1
   #   end
   # end
end

app/models/card_info.rb
class CardInfo < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  # validates :name, :age, :destination, :message , presence: true
  # validates :contact_no,   :presence => {:message => 'hello world, bad operation!'},
  #   :numericality => true,
  #     :length => { :minimum => 10, :maximum => 15 }
  # validates_format_of :email_id,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :hotel_name, :hotel_type, :location, :img_url, :place_id, presence: true
  belongs_to :place

  has_many :rooms
  has_many :reviews

  def set_rating
    number_of_reviews = reviews.count
    total_rating = 0
    current_hotel_rating = nil
    if number_of_reviews > 0
      reviews.each do |review|
        total_rating += review.rating
      end
      current_hotel_rating = total_rating.to_f/number_of_reviews.to_f
    end

    location
    self.rating = current_hotel_rating.to_f
    save!
  end
end

app/models/package.rb
class Package < ApplicationRecord
  validates :package_no, :package_name, :pack_description, :facilities,:price,:hotel_id, :img_url, :place_id, presence: true

   belongs_to :place
   belongs_to :hotel

end

app/models/payment_history.rb
class PaymentHistory < ApplicationRecord
  # has_one :user
  # validates :pay_type, inclusion: pay_type.keys
  # validates :pincode_digest, presence: true

  # validates :card_number, presence: true
  # def card_number_check
  #   @card_infos= CardInfo.find_by(card_number: card_number)
  #   unless card_number == @card_infos.card_number
  #     errors.add(:card_number, "Must be equal to the price to process further!")
  #   end
  # end
  enum pay_type: {
    "bkash" => 0,
    "credit card" => 1,

  }
  belongs_to :booking

end

app/models/place.rb
class Place < ApplicationRecord
  validates :place_name, :img_url, presence: true
  has_many :packages
  has_many :hotels
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :user

  after_save :set_hotel_rating
  def set_hotel_rating
    hotel.set_rating
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :room_no, :no_of_bed, :room_type,:room_description, :facilities,:price,:hotel_id, :img_url, :place_id, presence: true
  belongs_to :place
  belongs_to :hotel
  has_many :bookings


  # def available?
  #   @booking.each do |booking|
  #     if
  #     booking.check_in_date > check_in_date && booking.check_out_date > check_out_date
  #       return " helloooooooooo"
  #
  #
  #     end
  #
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
   has_many :bookings
   has_many :payment_histories
   has_many :blogs
   # has_many :contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :check_access
  def index
    @hotels=Hotel.order(count: :DESC).limit(3)
    @hotel=Hotel.order(rating: :DESC).limit(3)
    # @places= Place.(count: )
    # @hotels=Hotel.all
  end
  private
  def check_access
    #unless current_user.admin?
    unless user_signed_in? && current_user.admin?
      #unless @User.admin.find_by(id: session[:user_id])
      redirect_to new_user_session_path, alert: "You are not authorized to view this page"
      end
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_rooms_helper.rb
module UserRoomsHelper
end

app/views/home/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to 'Young Bird', root_path, class: "navbar-brand btn btn-outline-secondary" %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">

        <%= link_to 'Places', places_path, class: "nav-link " %>
      </li>
      <li class="nav-item">

        <%= link_to 'Packages', packages_path, class: "nav-link " %>
      </li>
      <li class="nav-item">

        <%= link_to 'Hotels', hotels_path, class: "nav-link " %>
      </li>
      <li class="nav-item">

        <%= link_to 'Rooms', rooms_path, class: "nav-link " %>
      </li>

      <li class="nav-item">

        <%= link_to 'Bookings', bookings_path, class: "nav-link " %>
      </li>
      <li class="nav-item">

        <%= link_to 'Payment', payment_histories_path, class: "nav-link " %>
      </li>



        <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, class: "nav-link btn btn-outline-secondary", :method => :delete, :data => { :no_turbolink => true } %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-outline-secondary" %>  </a>
        <% end %>
      </li>
    </ul>



  </div>

</nav>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to 'Young Bird', root_path, class: "navbar-brand btn btn-outline-secondary" %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">

        <%= link_to 'Places', user_places_index_path, class: "nav-link " %>
      </li>
      <li class="nav-item">

        <%= link_to 'Hotels', user_hotels_index_path, class: "nav-link " %>
      </li>
      <li class="nav-item">

        <%= link_to 'My bookings', my_bookings_index_path, class: "nav-link " %>
      </li>
      <li class="nav-item">

        <%= link_to 'Blogs', blogs_path, class: "nav-link " %>
      </li>

      <li class="nav-item">
        <%= link_to 'Video Tour', video_tours_index_path, class: "nav-link " %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Know Us
        </a>

        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to 'Contact Us',new_contact_path,class:"dropdown-item" %></li>
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
    <form class="form-inline d-flex my-2 my-lg-0"action="/search">
      <input class="form-control me-2" name="q" type="search" placeholder="Search Place" aria-label="Search">
<!--      <input class="form-control me-2" name="q2" type="search" placeholder="Search Place2" aria-label="Search">-->
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</li>
  </ul>
    <ul class="navbar-nav">
      <li class="nav-item">

        <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, class: "nav-link btn btn-outline-secondary", :method => :delete, :data => { :no_turbolink => true } %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-outline-secondary" %>  </a>
        <% end %>
      </li>
    </ul>



  </div>

</nav>