config/routes.rb
Rails.application.routes.draw do
  get 'video_tours/index'
  # resources :blogs
  get 'contacts/index'
  get 'payment_histories/index'
  get 'my_bookings/index'
  get 'user_rooms/index'
  get 'package_details/index'
  get 'user_hotels/index'
  get 'user_hotels/details'
  get 'user_places/index'
  get 'user_packages/index'
  get 'user_packages/details'
  get 'user_packages/filter'
  get 'video_tours/index'
  get 'video_tours/details'
  get 'blogs/blog_details'
  get 'details', to: "user_hotels#details"
  post 'rating', to: "user_hotels#set_hotel_rating"
  get 'search', to: "user_places#search"
  get 'filter_room', to: "user_rooms#filter_room"
  get 'min_max', to: "user_rooms#min_max"
  get 'filters_room', to: "user_packages#filters_room"
  get 'bookings/done'
  get 'contacts/done'
  get 'payment_histories/done'
  get 'rooms/justshow'
  get 'blogs/my_blog'
  resources :packages
  resources :bookings
  resources :contacts
  resources :payment_histories
  resources :rooms
  resources :hotels
  resources :places
  devise_for :users
  root to: 'home#index'

  # scope module: "users" do
  resources :blogs
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner

  has_rich_text :body
  def optimized_image(image,x,y)
    retrun image.variant(resize_to_fill: [x,y]).processed
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
   validates :name, :address, :contact_no, :email, :check_in_date, :check_out_date, presence: true
  validates :contact_no,   :presence => {:message => 'hello world, bad operation!'},
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  enum payment_status: {
    "unpaid" => 0,
    "paid" => 1,

  }
  belongs_to :user
  belongs_to :room
  has_one :payment_history

   # def paid_and_unpaid
   #   @booking = Booking.find(params[:booking_id])
   #   @booking.payment_history= PaymentHistory.find(params[:payment_history_id])
   #   if @booking.payment_histories_is_complete
   #     booking.payment_status = 1
   #   end
   # end
end

app/models/card_info.rb
class CardInfo < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  # validates :name, :age, :destination, :message , presence: true
  # validates :contact_no,   :presence => {:message => 'hello world, bad operation!'},
  #   :numericality => true,
  #     :length => { :minimum => 10, :maximum => 15 }
  # validates_format_of :email_id,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :hotel_name, :hotel_type, :location, :img_url, :place_id, presence: true
  belongs_to :place

  has_many :rooms
  has_many :reviews

  def set_rating
    number_of_reviews = reviews.count
    total_rating = 0
    current_hotel_rating = nil
    if number_of_reviews > 0
      reviews.each do |review|
        total_rating += review.rating
      end
      current_hotel_rating = total_rating.to_f/number_of_reviews.to_f
    end

    location
    self.rating = current_hotel_rating.to_f
    save!
  end
end

app/models/package.rb
class Package < ApplicationRecord
  validates :package_no, :package_name, :pack_description, :facilities,:price,:hotel_id, :img_url, :place_id, presence: true

   belongs_to :place
   belongs_to :hotel

end

app/models/payment_history.rb
class PaymentHistory < ApplicationRecord
  # has_one :user
  # validates :pay_type, inclusion: pay_type.keys
  # validates :pincode_digest, presence: true

  # validates :card_number, presence: true
  # def card_number_check
  #   @card_infos= CardInfo.find_by(card_number: card_number)
  #   unless card_number == @card_infos.card_number
  #     errors.add(:card_number, "Must be equal to the price to process further!")
  #   end
  # end
  enum pay_type: {
    "bkash" => 0,
    "credit card" => 1,

  }
  belongs_to :booking

end

app/models/place.rb
class Place < ApplicationRecord
  validates :place_name, :img_url, presence: true
  has_many :packages
  has_many :hotels
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :user

  after_save :set_hotel_rating
  def set_hotel_rating
    hotel.set_rating
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :room_no, :no_of_bed, :room_type,:room_description, :facilities,:price,:hotel_id, :img_url, :place_id, presence: true
  belongs_to :place
  belongs_to :hotel
  has_many :bookings


  # def available?
  #   @booking.each do |booking|
  #     if
  #     booking.check_in_date > check_in_date && booking.check_out_date > check_out_date
  #       return " helloooooooooo"
  #
  #
  #     end
  #
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
   has_many :bookings
   has_many :payment_histories
   has_many :blogs
   # has_many :contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/user_rooms_controller.rb
class UserRoomsController < ApplicationController
  require 'date'

  def index

    # @room.id=params[:room_id]
    # @rooms.price=params[:price]
      if session[:available_rooms].present?
        @rooms = Room.where(id: session[:available_rooms])
        session[:available_rooms] = nil
      else
        @rooms = nil
      end

    if params[:hotel_id].present?
      session[:hotel_id] = params[:hotel_id]
    end
    @hotel_id=session[:hotel_id]

  end
  def filter_room


    check_in_date = params[:check_in_date]
    check_out_date = params[:check_out_date]


    @rooms = Room.where(hotel_id: params[:hotel][:hotel_id])
    available_rooms =[]


    @rooms.each do |room|
      if room.bookings.count == 0
        available_rooms << room.id
      end


    room.bookings.each do |booking|
      # @booking.each do |booking|

      if
      booking.check_in_date > check_in_date.to_date && booking.check_in_date > check_out_date.to_date ||
        booking.check_out_date < check_in_date.to_date && booking.check_out_date <check_out_date.to_date

        available_rooms << room.id

                 puts "ssssssssssssssssssssssssssssssss"
                 puts "ssssssssssssssssssssssssssssssss"
                 puts available_rooms
                 puts "ssssssssssssssssssssssssssssssss"
                 puts "ssssssssssssssssssssssssssssssss"
                # available_rooms.push(room.id)
            # else
            #   available_rooms=nil

      end



      end
    end

    session[:available_rooms] = available_rooms.uniq
    redirect_to user_rooms_index_path(check_in_date: params[:check_in_date],check_out_date: params[:check_out_date],hotel_id: params[:hotel_id])
  end
  def min_max
    check_in_date = params[:check_in_date]
    check_out_date = params[:check_out_date]

    min = params[:min]
    max = params[:max]
    @rooms = Room.where('hotel_id = ? && price>=? && price<=?',params[:hotel][:hotel_id],min.to_i,max.to_i)
    available_rooms =[]
    @rooms.each do |room|
      available_rooms << room.id
    end


    session[:available_rooms] = available_rooms

    redirect_to user_rooms_index_path(min: params[:min],max: params[:max],hotel_id: params[:hotel_id],check_in_date: params[:check_in_date],check_out_date: params[:check_out_date])

    end

  end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_rooms_helper.rb
module UserRoomsHelper
end

app/views/user_rooms/index.html.erb
<div class="d-flex justify-content-around">
<section class="book">

<div class="container flex_space">
  <div class="text">
    <h1> <span> Search </span> Available Rooms </h1>
</div>
<div class="grid">
<!--  <form class ="grid">-->
<%= form_with(url: filter_room_path, method: :get, local: true) do |form| %>
    <%= form.label :check_in_date, "check_in_date :" %>
    <%= form.date_field :check_in_date, value: Date.today%>
  <%= form.label :check_out_date, "check_out_date:" %>
  <%= form.date_field :check_out_date,value: Date.tomorrow %><br>

  <%#= hidden_field(:hotel, :hotel_id, :value => params[:hotel_id]) %>
  <%= hidden_field(:hotel, :hotel_id, :value => @hotel_id) %>
    <%= form.submit "Search" %>
  <% end %>
 </div></div>
</section>

<section class="book">

  <div class="container flex_space">
    <div class="text">
      <h1> <span> Search </span> Available Rooms </h1>
    </div>
    <div class="grid">
      <!--  <form class ="grid">-->
      <%= form_with(url: min_max_path, method: :get, local: true) do |form| %>
        <%= form.label :min, "min :" %>
        <%= form.number_field :min, value: 1000%>
        <%= form.label :max, "max:" %>
        <%= form.number_field :max,value: 2000 %><br>
        <%= hidden_field(:hotel, :hotel_id, :value => @hotel_id) %>
        <%= hidden_field(:check_in_date=,:value => params[:check_in_date])%>
        <%= hidden_field(:check_out_date=,:value => params[:check_out_date])%>
        <%= form.submit "Search" %>
      <% end %>
    </div></div>
</section>
</div>

<div class="container" id="roomcontainer">
  <div class="row">
    <%unless @rooms.nil? %>
    <% @rooms.each do |room| %>
      <div class="col-md-4 border d-flex flex-column  align-items-center">
        <div class="room_image"> <%= image_tag(room.img_url) %></div>
        <h2><%= room.room_no %></h2>
        <p><%= "price" %></p>
        <h2><%= room.price %></h2>
        <div class=" btn btn-dark fw-bold">
        <%= link_to 'Book Room',new_booking_path(check_in_date: params[:check_in_date],check_out_date:params[:check_out_date],room_id: room , price: room) %>
        <%#= link_to 'Book Room',new_booking_path(check_in_date: params[:check_in_date],check_out_date:params[:check_out_date],@room.id=>params[:room_id],@room.price=>params[:price]) %>
        </div>
        </div>
        <%end %>
    <% end %>
  </div>
</div>

app/views/user_rooms/index.js.erb
$('#roomcontainer').removeClass("roomlist")