config/routes.rb
Rails.application.routes.draw do
  get 'video_tours/index'
  # resources :blogs
  get 'contacts/index'
  get 'payment_histories/index'
  get 'my_bookings/index'
  get 'user_rooms/index'
  get 'package_details/index'
  get 'user_hotels/index'
  get 'user_hotels/details'
  get 'user_places/index'
  get 'user_packages/index'
  get 'user_packages/details'
  get 'user_packages/filter'
  get 'video_tours/index'
  get 'video_tours/details'
  get 'blogs/blog_details'
  get 'details', to: "user_hotels#details"
  post 'rating', to: "user_hotels#set_hotel_rating"
  get 'search', to: "user_places#search"
  get 'filter_room', to: "user_rooms#filter_room"
  get 'min_max', to: "user_rooms#min_max"
  get 'filters_room', to: "user_packages#filters_room"
  get 'bookings/done'
  get 'contacts/done'
  get 'payment_histories/done'
  get 'rooms/justshow'
  get 'blogs/my_blog'
  resources :packages
  resources :bookings
  resources :contacts
  resources :payment_histories
  resources :rooms
  resources :hotels
  resources :places
  devise_for :users
  root to: 'home#index'

  # scope module: "users" do
  resources :blogs
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner

  has_rich_text :body
  def optimized_image(image,x,y)
    retrun image.variant(resize_to_fill: [x,y]).processed
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
   validates :name, :address, :contact_no, :email, :check_in_date, :check_out_date, presence: true
  validates :contact_no,   :presence => {:message => 'hello world, bad operation!'},
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  enum payment_status: {
    "unpaid" => 0,
    "paid" => 1,

  }
  belongs_to :user
  belongs_to :room
  has_one :payment_history

   # def paid_and_unpaid
   #   @booking = Booking.find(params[:booking_id])
   #   @booking.payment_history= PaymentHistory.find(params[:payment_history_id])
   #   if @booking.payment_histories_is_complete
   #     booking.payment_status = 1
   #   end
   # end
end

app/models/card_info.rb
class CardInfo < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  # validates :name, :age, :destination, :message , presence: true
  # validates :contact_no,   :presence => {:message => 'hello world, bad operation!'},
  #   :numericality => true,
  #     :length => { :minimum => 10, :maximum => 15 }
  # validates_format_of :email_id,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :hotel_name, :hotel_type, :location, :img_url, :place_id, presence: true
  belongs_to :place

  has_many :rooms
  has_many :reviews

  def set_rating
    number_of_reviews = reviews.count
    total_rating = 0
    current_hotel_rating = nil
    if number_of_reviews > 0
      reviews.each do |review|
        total_rating += review.rating
      end
      current_hotel_rating = total_rating.to_f/number_of_reviews.to_f
    end

    location
    self.rating = current_hotel_rating.to_f
    save!
  end
end

app/models/package.rb
class Package < ApplicationRecord
  validates :package_no, :package_name, :pack_description, :facilities,:price,:hotel_id, :img_url, :place_id, presence: true

   belongs_to :place
   belongs_to :hotel

end

app/models/payment_history.rb
class PaymentHistory < ApplicationRecord
  # has_one :user
  # validates :pay_type, inclusion: pay_type.keys
  # validates :pincode_digest, presence: true

  # validates :card_number, presence: true
  # def card_number_check
  #   @card_infos= CardInfo.find_by(card_number: card_number)
  #   unless card_number == @card_infos.card_number
  #     errors.add(:card_number, "Must be equal to the price to process further!")
  #   end
  # end
  enum pay_type: {
    "bkash" => 0,
    "credit card" => 1,

  }
  belongs_to :booking

end

app/models/place.rb
class Place < ApplicationRecord
  validates :place_name, :img_url, presence: true
  has_many :packages
  has_many :hotels
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :user

  after_save :set_hotel_rating
  def set_hotel_rating
    hotel.set_rating
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :room_no, :no_of_bed, :room_type,:room_description, :facilities,:price,:hotel_id, :img_url, :place_id, presence: true
  belongs_to :place
  belongs_to :hotel
  has_many :bookings


  # def available?
  #   @booking.each do |booking|
  #     if
  #     booking.check_in_date > check_in_date && booking.check_out_date > check_out_date
  #       return " helloooooooooo"
  #
  #
  #     end
  #
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
   has_many :bookings
   has_many :payment_histories
   has_many :blogs
   # has_many :contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :check_access
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index

    @rooms = Room.all
  end
  def justshow

    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:room_no, :no_of_bed, :room_type, :room_description, :facilities, :price, :img_url, :place_id, :hotel_id)
    end
  def check_access
    #unless current_user.admin?
    unless user_signed_in? && current_user.admin?
      #unless @User.admin.find_by(id: session[:user_id])
      redirect_to new_user_session_path, alert: "You are not authorized to view this page"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_rooms_helper.rb
module UserRoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
<%#= bootstrap_form_for(@room) do |room| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_no %>
    <%= form.text_field :room_no,class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :no_of_bed %>
    <%= form.text_field :no_of_bed %>
  </div>

  <div class="field">
    <%= form.label :room_type %>
    <%= form.number_field :room_type %>
  </div>

  <div class="field">
    <%= form.label :room_description %>
    <%= form.text_field :room_description %>
  </div>

  <div class="field">
    <%= form.label :facilities %>
    <%= form.text_field :facilities %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class=" control-group">
    <%= form.label :place, class: 'control-group' %>
    <div class=" control-group">
      <%= collection_select(:room, :place_id, Place.all, :id, :place_name, :prompt => true)%>
    </div></div>

  <div class=" control-group">
    <%= form.label :hotel, class: 'control-group' %>
    <div class=" control-group">
      <%= collection_select(:room, :hotel_id, Hotel.all, :id, :hotel_name, :prompt => true)%>
    </div></div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Room no</th>
      <th>No of bed</th>
      <th>Room type</th>
      <th>Room description</th>
      <th>Facilities</th>
      <th>Price</th>
      <th>Img url</th>
      <th>Place</th>
      <th>Hotel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_no %></td>
        <td><%= room.no_of_bed %></td>
        <td><%= room.room_type %></td>
        <td><%= room.room_description %></td>
        <td><%= room.facilities %></td>
        <td><%= room.price %></td>
        <td><%= room.img_url %></td>
        <td><%= room.place_id %></td>
        <td><%= room.hotel_id %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/justshow.html.erb
<% @rooms.each do |room| %>


  <div class="col-md-4 border d-flex flex-column  align-items-center">
    <div class="room_image"> <%= image_tag(room.img_url) %></div>
    <h2><%= room.room_no %></h2>
    <%= link_to 'Book Room',new_booking_path(room_id: room) %>
  </div>
<%end %>





</div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room no:</strong>
  <%= @room.room_no %>
</p>

<p>
  <strong>No of bed:</strong>
  <%= @room.no_of_bed %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @room.room_type %>
</p>

<p>
  <strong>Room description:</strong>
  <%= @room.room_description %>
</p>

<p>
  <strong>Facilities:</strong>
  <%= @room.facilities %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @room.img_url %>
</p>

<p>
  <strong>Place:</strong>
  <%= @room.place_id %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @room.hotel_id %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>