config/routes.rb
Rails.application.routes.draw do
  get 'video_tours/index'
  # resources :blogs
  get 'contacts/index'
  get 'payment_histories/index'
  get 'my_bookings/index'
  get 'user_rooms/index'
  get 'package_details/index'
  get 'user_hotels/index'
  get 'user_hotels/details'
  get 'user_places/index'
  get 'user_packages/index'
  get 'user_packages/details'
  get 'user_packages/filter'
  get 'video_tours/index'
  get 'video_tours/details'
  get 'blogs/blog_details'
  get 'details', to: "user_hotels#details"
  post 'rating', to: "user_hotels#set_hotel_rating"
  get 'search', to: "user_places#search"
  get 'filter_room', to: "user_rooms#filter_room"
  get 'min_max', to: "user_rooms#min_max"
  get 'filters_room', to: "user_packages#filters_room"
  get 'bookings/done'
  get 'contacts/done'
  get 'payment_histories/done'
  get 'rooms/justshow'
  get 'blogs/my_blog'
  resources :packages
  resources :bookings
  resources :contacts
  resources :payment_histories
  resources :rooms
  resources :hotels
  resources :places
  devise_for :users
  root to: 'home#index'

  # scope module: "users" do
  resources :blogs
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner

  has_rich_text :body
  def optimized_image(image,x,y)
    retrun image.variant(resize_to_fill: [x,y]).processed
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
   validates :name, :address, :contact_no, :email, :check_in_date, :check_out_date, presence: true
  validates :contact_no,   :presence => {:message => 'hello world, bad operation!'},
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  enum payment_status: {
    "unpaid" => 0,
    "paid" => 1,

  }
  belongs_to :user
  belongs_to :room
  has_one :payment_history

   # def paid_and_unpaid
   #   @booking = Booking.find(params[:booking_id])
   #   @booking.payment_history= PaymentHistory.find(params[:payment_history_id])
   #   if @booking.payment_histories_is_complete
   #     booking.payment_status = 1
   #   end
   # end
end

app/models/card_info.rb
class CardInfo < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  # validates :name, :age, :destination, :message , presence: true
  # validates :contact_no,   :presence => {:message => 'hello world, bad operation!'},
  #   :numericality => true,
  #     :length => { :minimum => 10, :maximum => 15 }
  # validates_format_of :email_id,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :hotel_name, :hotel_type, :location, :img_url, :place_id, presence: true
  belongs_to :place

  has_many :rooms
  has_many :reviews

  def set_rating
    number_of_reviews = reviews.count
    total_rating = 0
    current_hotel_rating = nil
    if number_of_reviews > 0
      reviews.each do |review|
        total_rating += review.rating
      end
      current_hotel_rating = total_rating.to_f/number_of_reviews.to_f
    end

    location
    self.rating = current_hotel_rating.to_f
    save!
  end
end

app/models/package.rb
class Package < ApplicationRecord
  validates :package_no, :package_name, :pack_description, :facilities,:price,:hotel_id, :img_url, :place_id, presence: true

   belongs_to :place
   belongs_to :hotel

end

app/models/payment_history.rb
class PaymentHistory < ApplicationRecord
  # has_one :user
  # validates :pay_type, inclusion: pay_type.keys
  # validates :pincode_digest, presence: true

  # validates :card_number, presence: true
  # def card_number_check
  #   @card_infos= CardInfo.find_by(card_number: card_number)
  #   unless card_number == @card_infos.card_number
  #     errors.add(:card_number, "Must be equal to the price to process further!")
  #   end
  # end
  enum pay_type: {
    "bkash" => 0,
    "credit card" => 1,

  }
  belongs_to :booking

end

app/models/place.rb
class Place < ApplicationRecord
  validates :place_name, :img_url, presence: true
  has_many :packages
  has_many :hotels
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :user

  after_save :set_hotel_rating
  def set_hotel_rating
    hotel.set_rating
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :room_no, :no_of_bed, :room_type,:room_description, :facilities,:price,:hotel_id, :img_url, :place_id, presence: true
  belongs_to :place
  belongs_to :hotel
  has_many :bookings


  # def available?
  #   @booking.each do |booking|
  #     if
  #     booking.check_in_date > check_in_date && booking.check_out_date > check_out_date
  #       return " helloooooooooo"
  #
  #
  #     end
  #
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
   has_many :bookings
   has_many :payment_histories
   has_many :blogs
   # has_many :contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/package_details_controller.rb
class PackageDetailsController < ApplicationController
  def index
    @package =Package.find(params[:package_id])
    # @place=Place.find_by_id(params[:place_id])
    # @packages=@place.packages
  end
  def filter
    @package =Package.find(params[:package_id])
  end


end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/package_details_helper.rb
module PackageDetailsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_rooms_helper.rb
module UserRoomsHelper
end

app/views/package_details/filter.html.erb
<%= form_with(url: filter_room_path, method: :get, local: true) do |form| %>
  <%= form.label :check_in_date, "check_in_date :" %>
  <%= form.date_field :check_in_date,value: Date.today %>
  <%= form.label :check_out_date, "check_out_date:" %>
  <%= form.date_field :check_out_date,value: Date.tomorrow %>
  <%= form.submit "Search" %>
<% end %>

app/views/package_details/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>
<%= form_with(url: filters_room_path, method: :get, local: true) do |form| %>
  <%= form.label :check_ins_date, "check_in_date :" %>
  <%= form.date_field :check_ins_date,value: Date.today %>
  <%= form.label :check_outs_date, "check_out_date:" %>
  <%= form.date_field :check_outs_date ,value: Date.today%>
  <%= form.submit "Search" %>
<% end %>
<div class="container mt-3">

<div class =" imagee">

    <div class="col-md-4  d-flex flex-row  bd-higlight mb-3 ">
      <div class="pl_image  ">
        <div class="p-2 bd-highlight"> <h3>Place </h3>
          <img class=" img-resposive img-resize ">
          <%= image_tag(@package.place.img_url) %>
        <%#= image_tag(@package.place.image_url) %>
        <h2><%= @package.place.place_name %></h2>
      </div>
    </div>
      <div class="ht_image ">
        <div class="p-2 bd-highlight"> <h3>Place </h3>

        <%= image_tag(@package.hotel.img_url) %>
        <%#= image_tag(@package.place.image_url) %>
        <h2><%= @package.hotel.hotel_name %></h2>
        </div>
      </div>
      <div class="rm_image img-fluid ">
        <div class="p-2 bd-highlight"> <h3> Room </h3>


        <%#= image_tag(@package.room.img_url) %>
        <%#= image_tag(@package.place.image_url) %>

        <h2>Room_type:<%= @package.room.room_type %></h2>
          <h2>No_Of_Bed: <%= @package.room.no_of_bed %></h2>
        </div></div>


      </div>
    </div>

</div>

<%= link_to 'Details', user_packages_filter_path(room_type: @room, no_of_bed: @room,hotel_id: @hotel,place_id: @place ,package_id: @package) %>


  <%#= link_to 'Book', new_order_path(package_id: @package) %>
</div>


</div>